
[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
if = 0
depends = 'deoplete.nvim'
on_if = 0
# on_ft = 'java'
hook_post_source = '''
au FileType java setl omnifunc=javacomplete#Complete
'''

[[plugins]]
repo = 'osyo-manga/vim-monster'
# on_if = 0
on_ft = 'ruby'
hook_add = '''
" let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
\   "ruby" : '[^. *\t]\.\w*\|\h\w*::',
\}
'''

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_if = 0
# on_ft = 'ruby'

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_if = 0
# on_ft = 'ruby'
